### ISSUE TITLE
一个验证时的问题

### ISSUE THREAD

**Issue by tqinger** [Flionay/segmentation-learning-experiment#2]
您好，我在使用自己数据集训练，在验证时时会报错boolean index did not match indexed array along dimension 0; dimension is 320 but corresponding boolean dimension is 102400，请问为什么呢

**Comment by Flionay** [comment]
你好，可以打个断点调试一下，我这里不知道您具体多少行。 大概意思是你有类似a[True,True,False],类似这样的索引操作，bool索引是102400个，而数组是有320个，查一下就可以
